In [1]:
# numpy 라이브러리 import
import numpy as np

In [2]:
# 1,2,3,4,5로 구성된 python list 생성하여, 변수 a에 할당
a = [1, 2, 3, 4, 5]
a

[1, 2, 3, 4, 5]

In [3]:
# 1,2,3,4,5로 구성된 numpy 배열 생성하여, 변수 b에 할당
b = np.array([1,2,3,4,5])
b

array([1, 2, 3, 4, 5])

In [4]:
# array 함수를 이용해 2 X 3 배열 생성
data = np.array([[1,2], [3,4], [5,6]])

In [5]:
# 자료형 조회
type(data)

numpy.ndarray

In [6]:
# 배열의 차원 조회
data.ndim

2

In [7]:
# 배열의 각 차원의 크기를 조회
data.shape

(3, 2)

In [8]:
# 전체 요소 갯수를 조회
data.size

6

In [9]:
# 배열에 저장된 자료형을 조회
data.dtype

dtype('int32')

In [10]:
# 배열의 전체 원소가 차지하는 byte의 크기를 조회
data.nbytes

24

In [11]:
# 난수 발생기의 seed값을 0으로 설정
np.random.seed(0)

In [12]:
# 1차원 0~10까지의 정수형 난수 배열 생성. 크기=6
np.random.randint(10, size=6)

array([5, 0, 3, 3, 7, 9])

In [13]:
# 2차원 0~10까지의 정수형 난수 배열 생성. 크기=(3,4)
np.random.randint(10, size=(3,4))

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [14]:
# 3차원 0~10까지의 정수형 난수 배열 생성. 크기=(3,4,5)
np.random.randint(10, size=(3,4,5))

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [15]:
# 난수 발생기의 seed값을 0으로 설정
np.random.seed(0)

# 2차원 정수형 난수 배열 생성하여 변수 x에 할당. 크기=(3,3)
x = np.random.randint(10, size=(3,3))
x

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [16]:
# 기본 산술연산자를 활용하여, 자연스럽게 배열의 각 원소에 산술연산 가능
# 배열의 각 원소에 + 5
x + 5

array([[10,  5,  8],
       [ 8, 12, 14],
       [ 8, 10,  7]])

In [17]:
# 배열의 각 원소에 * 2
x * 2

array([[10,  0,  6],
       [ 6, 14, 18],
       [ 6, 10,  4]])

In [18]:
# 배열의 최소, 최대, 평균, 표준편차
x.min(), x.max(), x.mean(), x.std()

(0, 9, 4.111111111111111, 2.5579698740491863)

In [19]:
# 크기가 (6,6)인 배열을 생성
a = np.zeros((6,6), dtype='int32')
for idx0 in range(6):
    for idx1 in range(6):
        a[idx0, idx1] = idx0* 10 + idx1 
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [20]:
a[(0, 1, 2, 3, 4), (1, 2, 3, 4, 5)]

array([ 1, 12, 23, 34, 45])

In [21]:
a[3:, [0, 3, 5]]

array([[30, 33, 35],
       [40, 43, 45],
       [50, 53, 55]])

In [22]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
a[mask, 2]

array([ 2, 22, 52])